export const ROUTES = {
    home: '/',
    register: '/register',
    tasks: '/tasks',
    notifications: '/notifications',
    profile: '/profile',
    taskDetail: (id: string) => `/tasks/${id}`,
} as const;

export const UI_TEXT_EN = {
    auth: {
        eyebrow: 'Task Portal',
        registerTitle: 'Create an account',
        registerDescription: 'Create your account to save your tasks and track your notifications.',
        loginTitle: 'Log in',
        loginDescription: 'Pick up where you left off with your tasks and notifications.',
        nameLabel: 'Full name',
        namePlaceholder: 'Enter your name',
        emailLabel: 'Email',
        emailPlaceholder: 'example@email.com',
        passwordLabel: 'Password',
        passwordHint: 'Password must be at least 8 characters long.',
        registerButton: 'Create account',
        registeringButton: 'Creating account...',
        loginButton: 'Log in',
        loggingInButton: 'Logging in...',
        haveAccount: 'Already have an account?',
        loginAction: 'Log in',
        noAccount: "Don't have an account yet?",
        registerAction: 'Create account',
        requiredError: 'Please fill in the required fields.',
        emailTakenError: 'This email address is already in use.',
        invalidCredentialsError: 'Invalid email or password.',
        requestError: 'Transaction could not be completed. Please try again.',
    },

    topBar: {
        logo: 'T',
        eyebrow: 'Portal',
        title: 'Task Portal',
        navigationLabel: 'Main navigation',
        createTaskLink: 'Create Task',
        tasksLink: 'Tasks',
        profileLink: 'Profile',
        bellLabel: 'Notifications',
        bellIcon: '🔔',
        logoutButton: 'Log out',
        loggingOutButton: 'Logging out...',
        logoutError: 'Could not log out. Please try again.',
        dueAlertTitle: 'Task due time',
        dueAlertMessage: 'It is time for your scheduled task.',
        dueAlertDetailButton: 'Go to task',
        dueAlertCloseButton: 'Close',
    },

	taskStatus: {
		pending: 'Pending',
		in_progress: 'In Progress',
		completed: 'Completed',
	},

	tasks: {
		eyebrow: 'Tasks',
		title: 'Task list',
		countSuffix: 'tasks',
		createButton: 'Create new task',
		loading: 'Loading tasks...',
		empty: 'No tasks added yet.',
		loadError: 'Failed to load tasks.',
		emptyDescription: 'No description provided.',
		detailButton: 'View details',
		deleteButton: 'Delete task',
		deletingButton: 'Deleting...',
		deleteConfirm: 'Are you sure you want to delete this task?',
		deleteError: 'Could not delete task. Please try again.',
	},

	taskDetail: {
		eyebrow: 'Task Details',
		descriptionTitle: 'Description',
		emptyDescription: 'No description provided.',
		statusLabel: 'Status',
		statusUpdating: 'Saving...',
		statusUpdateError: 'Failed to update status. Please try again.',
		dueAtLabel: 'Due date',
		createdAtLabel: 'Created at',
		newTaskButton: 'New task',
		notificationsButton: 'Notifications',
		loading: 'Loading task...',
		notFound: 'Task not found.',
		loadError: 'Failed to load task details.',
		backHomeButton: 'Back to home',
		deleteButton: 'Delete task',
		deletingButton: 'Deleting...',
		deleteConfirm: 'Are you sure you want to delete this task?',
		deleteError: 'Could not delete task. Please try again.',
	},

	notifications: {
		eyebrow: 'Notifications',
		title: 'Task alerts',
		loading: 'Loading notifications...',
		empty: 'No notifications to display right now.',
		loadError: 'Failed to load notifications.',
		countSuffix: 'unread notifications',
		createdAtLabel: 'Created at:',
		createTaskButton: 'Create task',
		detailButton: 'Detail',
		markAllReadButton: 'Mark all as read',
		markReadError: 'Could not mark notification as read.',
		markAllReadError: 'Could not mark notifications as read.',
	},

	home: {
		requiredFieldsError: 'Task title and due date are required.',
		createError: 'Could not create task.',
		formEyebrow: 'Task Title',
		formTitle: 'Create new task',
		titleLabel: 'Task title',
		titlePlaceholder: 'Enter task title...',
		descriptionLabel: 'To-do items',
		descriptionPlaceholder: 'Write task steps...',
		dueAtLabel: 'Notification time',
		dueAtHint: 'Alarm triggers at your selected date and time.',
		savingButton: 'Saving...',
		saveButton: 'Save task',
	},

	profile: {
		eyebrow: 'Profile',
		title: 'Profile Information',
		loading: 'Loading profile...',
		loadError: 'Failed to load profile information.',
		name: 'Name field cannot be left blank.',
		IsNotFindValue: 'Failed to update profile.',
		nameLabel: 'First Name',
		surnameLabel: 'Last Name',
		emailLabel: 'Email',
		bdayLabel: 'Date of Birth',
		namePlaceholder: 'Enter your first name',
		surnamePlaceholder: 'Enter your last name',
		emailPlaceholder: 'Enter your email address',
		bdayPlaceholder: 'Enter your date of birth',
		savingButton: 'Saving...',
		saveButton: 'Update Profile',
	},
} as const;