export const ROUTES = {
	home: '/',
	register: '/register',
	tasks: '/tasks',
	notifications: '/notifications',
	profile:'/profile',
	taskDetail: (id: string) => `/tasks/${id}`,
} as const;

export const UI_TEXT = {
	auth: {
		eyebrow: 'Görev Portalı',
		registerTitle: 'Hesap oluştur',
		registerDescription: 'Görevlerini kaydetmek ve bildirimlerini takip etmek için hesabını oluştur.',
		loginTitle: 'Giriş yap',
		loginDescription: 'Görevlerine ve bildirimlerine kaldığın yerden devam et.',
		nameLabel: 'Ad soyad',
		namePlaceholder: 'Adını yaz',
		emailLabel: 'E-posta',
		emailPlaceholder: 'ornek@email.com',
		passwordLabel: 'Şifre',
		passwordHint: 'Şifre en az 8 karakter olmalıdır.',
		registerButton: 'Hesap oluştur',
		registeringButton: 'Hesap oluşturuluyor...',
		loginButton: 'Giriş yap',
		loggingInButton: 'Giriş yapılıyor...',
		haveAccount: 'Zaten hesabın var mı?',
		loginAction: 'Giriş yap',
		noAccount: 'Henüz hesabın yok mu?',
		registerAction: 'Hesap oluştur',
		requiredError: 'Lütfen zorunlu alanları doldur.',
		emailTakenError: 'Bu e-posta adresi zaten kullanılıyor.',
		invalidCredentialsError: 'E-posta veya şifre hatalı.',
		requestError: 'İşlem tamamlanamadı. Lütfen tekrar dene.',
	},

	topBar: {
		logo: 'T',
		eyebrow: 'Portal',
		title: 'Görev Portalı',
		navigationLabel: 'Ana navigasyon',
		createTaskLink: 'Görev Oluştur',
		tasksLink: 'Görevler',
		profileLink: 'Profil',
		bellLabel: 'Bildirimler',
		bellIcon: '🔔',
		logoutButton: 'Çıkış yap',
		loggingOutButton: 'Çıkılıyor...',
		logoutError: 'Çıkış yapılamadı. Lütfen tekrar dene.',
		dueAlertTitle: 'Görev zamanı geldi',
		dueAlertMessage: 'Planladığın görevin zamanı geldi.',
		dueAlertDetailButton: 'Göreve git',
		dueAlertCloseButton: 'Kapat',
	},

	taskStatus: {
		pending: 'Bekliyor',
		in_progress: 'İşlemde',
		completed: 'Tamamlandı',
	},

	tasks: {
		eyebrow: 'Görevler',
		title: 'Görev listesi',
		countSuffix: 'görev',
		createButton: 'Yeni görev oluştur',
		loading: 'Görevler yükleniyor...',
		empty: 'Henüz görev eklenmedi.',
		loadError: 'Görevler yüklenemedi.',
		emptyDescription: 'Açıklama eklenmedi.',
		detailButton: 'Detaya git',
		deleteButton: 'Görevi sil',
		deletingButton: 'Siliniyor...',
		deleteConfirm: 'Bu görevi silmek istediğine emin misin?',
		deleteError: 'Görev silinemedi. Lütfen tekrar dene.',
	},

	taskDetail: {
		eyebrow: 'Görev Detayı',
		descriptionTitle: 'Açıklama',
		emptyDescription: 'Açıklama eklenmedi.',
		statusLabel: 'Durum',
		statusUpdating: 'Kaydediliyor...',
		statusUpdateError: 'Durum güncellenemedi. Lütfen tekrar dene.',
		dueAtLabel: 'Son teslim',
		createdAtLabel: 'Oluşturulma',
		newTaskButton: 'Yeni görev',
		notificationsButton: 'Bildirimler',
		loading: 'Görev yükleniyor...',
		notFound: 'Görev bulunamadı.',
		loadError: 'Görev detayları yüklenemedi.',
		backHomeButton: 'Ana sayfaya dön',
		deleteButton: 'Görevi sil',
		deletingButton: 'Siliniyor...',
		deleteConfirm: 'Bu görevi silmek istediğine emin misin?',
		deleteError: 'Görev silinemedi. Lütfen tekrar dene.',
	},

	notifications: {
		eyebrow: 'Bildirimler',
		title: 'Görev uyarıları',
		loading: 'Bildirimler yükleniyor...',
		empty: 'Şu an gösterilecek bildirim yok.',
		loadError: 'Bildirimler yüklenemedi.',
		countSuffix: 'okunmamış bildirim',
		createdAtLabel: 'Oluşturuldu:',
		createTaskButton: 'Görev oluştur',
		detailButton: 'Detay',
		markAllReadButton: 'Tümünü okundu işaretle',
		markReadError: 'Bildirim okundu olarak işaretlenemedi.',
		markAllReadError: 'Bildirimler okundu olarak işaretlenemedi.',
	},

	home: {
		requiredFieldsError: 'Görev başlığı ve son tarih zorunludur.',
		createError: 'Görev oluşturulamadı.',
		formEyebrow: 'Görev Başlığı',
		formTitle: 'Yeni görev oluştur',
		titleLabel: 'Görev başlığı',
		titlePlaceholder: 'Görev başlığını girin...',
		descriptionLabel: 'Yapılacak işler',
		descriptionPlaceholder: 'Yapılacak iş adımlarını yazın...',
		dueAtLabel: 'Bildirim zamanı',
		dueAtHint: 'Alarm, seçtiğin tarih ve saat geldiğinde oluşur.',
		savingButton: 'Kaydediliyor...',
		saveButton: 'Görevi kaydet',
	},

	profile: {
		eyebrow: 'Profil',
		title: 'Profil Bilgileri',
		loading: 'Profil bilgileri yükleniyor...',
		loadError: 'Profil bilgileri yüklenemedi.',
		name: 'İsim kısmı boş kalmamalı',
		IsNotFindValue: 'Profil bilgileri güncellenemedi.',
		nameLabel: 'Ad',
		surnameLabel: 'Soyad',
		emailLabel: 'E-posta',
		bdayLabel: 'Doğum Tarihi',
		namePlaceholder: 'Adını yaz',
		surnamePlaceholder: 'Soyadını yaz',
		emailPlaceholder: 'E-posta adresinizi giriniz',
		bdayPlaceholder: 'Doğum tarihinizi giriniz',
		savingButton: 'Kaydediliyor...',
		saveButton: 'Profili Güncelle',
	},
} as const;
